services:
  frontend: # Mudei de 'server' para 'frontend' para ficar mais claro
    build:
      context: .
      dockerfile: Dockerfile
      # Passamos as variáveis aqui para o Dockerfile usar na hora do build
      args:
        VITE_SERVER_URL: "${VITE_SERVER_URL}"
        VITE_WEBSOCKET_URL: "${VITE_WEBSOCKET_URL}"
    container_name: listfy-frontend
    restart: always
    ports:
      - "4000:4000" # O 'serve' roda na 3000 conforme definimos no CMD acima
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
      - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}