services:
  server:
    build: .
    container_name: listfy-frontend
    volumes: 
      - "./:/usr/app"
      - /usr/app/node_modules
    ports: 
      - 5173:5173
    environment:
      - VITE_SERVER_URL=http://localhost:3000/
      - VITE_WEBSOCKET_URL=http://localhost:3005/